# SQL credentials are in the helper-sql config, in case you're wondering.

# Messages
messages:
  join-quest-progress: "&7Welcome back, %3$s. You are currently &a%1$s% &7through your %2$s &7Quest. Use &e/quests &7for more information."
  join-quest-expired: "&7Welcome back, %2$s. The time to complete the %1$s &7Quest has &cexpired&7. Use &e/quests &7to try again."
  join-quest-available: "&7Welcome, %1$s. There are new quests available! Use &e/quests &7to open the quests menu."
